PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX gip: <http://gipuzkoa.eus/resource/>

SELECT ?pop 
WHERE {
    gip:bilbo owl:sameAs ?town 
    SERVICE <https://query.wikidata.org/sparql> {
        ?town <http://www.wikidata.org/prop/direct/P1082> ?pop .
    }
} 


