PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX gip_prop: <http://gipuzkoa.eus/prop/>

SELECT ?museo ?obras
{
  {
    
    { # ----- Begin optimization group 1 -----
      
      ?museo rdf:type dbpedia:museum . #    Collection size: 3  Predicate collection size: 53   Unique subjects: 44 Unique objects: 9   Current complexity: 3
      
    } # ----- End optimization group 1 -----
    # ESTIMATED NUMBER OF ITERATIONS: 3
    
  }
  MINUS
  {
    
    { # ----- Begin optimization group 2 -----
      
      ### RANGE TRIPLE PATTERN ([ obras in ["300"^^<http://www.w3.org/2001/XMLSchema#integer> ; null) ]) # Collection size: 2
      FILTER (?obras > 300)
      ?museo gip_prop:kopurua ?obras . #    Collection size: 3  Predicate collection size: 3    Unique subjects: 3  Unique objects: 3   Current complexity: 2
      
    } # ----- End optimization group 2 -----
    # ESTIMATED NUMBER OF ITERATIONS: 2
    
  }
}

# NOTE: Optimization groups are evaluated one after another exactly in the given order.
# If there are too many optimization groups consisting of a single statement pattern,
# then one should try to relocate the following clauses by hand:
# VALUES, BIND, OPTIONAL, property paths with '*' and/or '+' (the latter can be also surrounded with brackets).
# Sub-SELECTs will always be evaluated first.